Feature: create a script to ontoportal docker api UI
ontoportal-lirmm/ontoportal_docker pull request #4
Opened 2024-06-05 14:38 UTC by syphax-bouazzouni

2024-06-10 21:03 UTC, imadbourouche requested changes

2024-06-10 21:03 UTC, imadbourouche commented on ontoportal
> +  clean "$2"
change this to update

2024-06-10 21:03 UTC, imadbourouche commented on run
> +        "bin/run_cron.sh bundle exec rake user:create[admin,admin@nodomain.org,password]'"
add ' in all the bin/run_cron.sh commands

2024-06-10 21:03 UTC, imadbourouche commented on run
> +        'docker compose  -f docker-compose_api.yml --profile 4store  down --volumes'
change this to ./ontoportl clean because there is no docker-compose.yml

2024-06-10 21:03 UTC, imadbourouche commented on bin/run_cron.sh
> +	run_cron "$env_path" "$2"
remove run_cron

2024-06-10 21:03 UTC, imadbourouche commented on ontoportal
> +clean() {
in clean, should  we remove docker compose files for api and ui also ? to each time we start the ontoportal we start it with the new docker compose files

2024-06-10 21:03 UTC, imadbourouche commented on bin/run_ui.sh
> +  docker logs ui-service -f
we can do : `docker exec -it ui-service tail -f log/production.log` like in the run_api

2024-06-10 21:03 UTC, imadbourouche commented on ontoportal
> +start() {
it's good to call update before starting the script to not fall in the error of old images

2024-06-10 21:03 UTC, imadbourouche commented on run
> +if status_ok; then
status_ok does not exist in the run script

2024-06-10 21:03 UTC, imadbourouche commented on run
> +source utils/loading_animation.sh "[+] Waiting for the server http://localhost:9393 to be up..." "http://localhost:9393" 300
this is being checked in the run_api.sh script

2024-07-02 18:30 UTC, syphax-bouazzouni commented on ontoportal
> +	clone_ongologies_linked_data(){
no need for this now with the new SOLR

2024-07-02 18:30 UTC, syphax-bouazzouni commented on ontoportal
> +	bash_cmd="bundle exec rackup --host 0.0.0.0  --env=development --port 9393"
make this customizable to run the production server or the development server.

2024-07-02 18:30 UTC, syphax-bouazzouni commented on bin/deploy.sh
> +	awk -v SERVICE="$SERVICE" '/^SERVICE=/{sub(/=.*/, "=" SERVICE)} 1' .env >temp && mv temp .env
awk does not work in Mac OS

2024-07-02 18:30 UTC, syphax-bouazzouni commented on bin/run_ui.sh
> +  docker logs ui-service -f
why ?

2024-07-02 18:30 UTC, syphax-bouazzouni commented on ontoportal
> +  sed -i "s/^SERVICE=.*/SERVICE=$SERVICE/" ".env"
sed does not work in MAC OS

2024-07-15 18:30 UTC, imadbourouche approved these changes

2024-07-15 19:21 UTC, merged